name: "Tag, Release"
on:
  push:
    branches:
      - main
    paths:
      - "Htmx.module.php"
jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    env:
      VERSION_FILE: "Htmx.module.php"
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
      - name: Extract module version
        id: get_version
        run: |
          VERSION=$(php -r "\$c = file_get_contents('${{ env.VERSION_FILE }}'); preg_match('/[\'\"].*?version.*?[\'\"]\s*=>\s*[\'\"]?([0-9\.]+)[\'\"]?/', \$c, \$m); \$v = \$m[1] ?? ''; if(is_numeric(\$v) && strpos((string)\$v, '.') === false) { \$v = (int)\$v; \$major = intval(\$v / 100); \$minor = intval(\$v / 10) % 10; \$micro = \$v % 10; \$v = \"\$major.\$minor.\$micro\"; } echo \$v;")

          if [ -z "$VERSION" ]; then
            echo "::error::Could not find the version number in ${{ env.VERSION_FILE }}"
            exit 1
          fi

          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Create Git Tag and GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          TAG="v${{ steps.get_version.outputs.version }}"
          echo "Generated Tag: $TAG"
          git tag $TAG
          git push origin $TAG
          
          # Find the previous tag mapping to the current branch
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          
          echo "## What's Changed" > release_notes.md
          if [ -n "$PREV_TAG" ]; then
            git log --format="* %s by **%an** in %h" $PREV_TAG..HEAD >> release_notes.md
            echo "" >> release_notes.md
            
            echo "## Contributors" >> release_notes.md
            git log --format="* %an" $PREV_TAG..HEAD | awk '!seen[$0]++' >> release_notes.md
            echo "" >> release_notes.md
            
            echo "**Full Changelog**: https://github.com/$REPO/compare/$PREV_TAG...$TAG" >> release_notes.md
          else
            git log --format="* %s by **%an** in %h" HEAD >> release_notes.md
            echo "" >> release_notes.md
            
            echo "## Contributors" >> release_notes.md
            git log --format="* %an" HEAD | awk '!seen[$0]++' >> release_notes.md
            echo "" >> release_notes.md
            
            echo "**Full Changelog**: https://github.com/$REPO/commits/$TAG" >> release_notes.md
          fi
          
          gh release create $TAG -F release_notes.md
